// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

namespace api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210719211232_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("api.Models.Caixa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("descricao")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Caixas");
                });

            modelBuilder.Entity("api.Models.CaixaNotas", b =>
                {
                    b.Property<int>("CaixaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("CaixaId", "NotaId");

                    b.HasIndex("NotaId");

                    b.ToTable("CaixasNotas");
                });

            modelBuilder.Entity("api.Models.Nota", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descricao")
                        .HasColumnType("TEXT");

                    b.Property<float>("valor")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Notas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            descricao = "R$ 50",
                            valor = 50f
                        },
                        new
                        {
                            id = 2,
                            descricao = "R$ 20",
                            valor = 20f
                        },
                        new
                        {
                            id = 3,
                            descricao = "R$ 10",
                            valor = 10f
                        },
                        new
                        {
                            id = 4,
                            descricao = "R$ 5",
                            valor = 5f
                        },
                        new
                        {
                            id = 5,
                            descricao = "R$ 2",
                            valor = 2f
                        });
                });

            modelBuilder.Entity("api.Models.CaixaNotas", b =>
                {
                    b.HasOne("api.Models.Caixa", "Caixa")
                        .WithMany("NotasNoCaixa")
                        .HasForeignKey("CaixaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Nota", "Nota")
                        .WithMany()
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caixa");

                    b.Navigation("Nota");
                });

            modelBuilder.Entity("api.Models.Caixa", b =>
                {
                    b.Navigation("NotasNoCaixa");
                });
#pragma warning restore 612, 618
        }
    }
}
